# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LetsWaitDating' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LetsWaitDating

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTActionSheet',
    'RCTLinkingIOS',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTText',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTWebSocket', # Needed for debugging
    'RCTImage',
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]

   # Third party deps podspec link
  pod 'yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'DoubleConversion',
    :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec",
    :inhibit_warnings => true

  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-haptic-feedback', :path => '../node_modules/react-native-haptic-feedback'
  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  # pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-safari-view', :podspec => '../node_modules/react-native-safari-view/react-native-safari-view.podspec'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  target 'LetsWaitDatingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'LetsWaitDating-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LetsWaitDating-tvOS

  target 'LetsWaitDating-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end